### ISSUE TITLE
README.md pass transformer list in

### ISSUE THREAD

**Issue by ZuowenWang0000** [stanford-futuredata/equivariant-transformers#1]
Hi Kai Sheng, thanks a lot for your work!
there is a small mistake in the README. In order to pass a list (for the transformers) using command line, We pass it as a string, namely
--tfs "[ShearX, HyperbolicRotation]"
Am I correct?

**Comment by kaishengtai** [comment]
Thanks for pointing this out -- I've fixed this in the README.

It works if you leave out the space: [ShearX,HyperbolicRotation], but if there's whitespace then the quotes are necessary.
